In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# checking pandas version
print(f"Pandas version: {pd.__version__}")

Pandas version: 3.0.1

#### Pandas Series

In [7]:
ml_marks = [50, 70, 82, 63, 38]
type(ml_marks)

list

In [8]:
# creating a pandas series
ml_series = pd.Series(ml_marks)
ml_series

0    50
1    70
2    82
3    63
4    38
dtype: int64

In [9]:
type(ml_series)

pandas.Series

In [10]:
# Creating a series with a custom index
ml_series_idx = pd.Series(
    ml_marks,
    index=['Vanessa', 'Christine', 'Peter', 'Diana', 'Racheal'],
    name='ML Marks'
)
ml_series_idx

Vanessa      50
Christine    70
Peter        82
Diana        63
Racheal      38
Name: ML Marks, dtype: int64

In [11]:
# Accessing elements
print(f'The first element in "ML series" is {ml_series[0]}')
print(f'The first element in "ML series" is {ml_series.loc[0]}')
print(f'The first element in "ML series" is {ml_series.iloc[0]}')

The first element in "ML series" is 50
The first element in "ML series" is 50
The first element in "ML series" is 50

In [ ]:
print(f'Peter got {ml_series_idx["Peter"]} in the ML course')
print(f'Peter got {ml_series_idx.loc["Peter"]} in the ML course')
print(f'Peter got {ml_series_idx.iloc["Peter"]} in the ML course') # gives an error. Why?
#it gives an error because the index isn't an integer

Peter got 82 in the ML course
Peter got 82 in the ML course

TypeError: Cannot index by location index with a non-integer key

#### Pandas DataFrame

In [13]:
# Creating a dataframe from a dictionary. Keys are column names and values are column values
example_df = pd.DataFrame({'Name': ['Vanessa', 'Christine', 'Peter', 'Diana', 'Racheal'],
                    'Age': [18, 20, 25, 30, 35],
                    'ML mark': [50, 70, 82, 63, 38]
                   })
example_df

        Name  Age  ML mark
0    Vanessa   18       50
1  Christine   20       70
2      Peter   25       82
3      Diana   30       63
4    Racheal   35       38

In [14]:
# creating a dataframe from a list of dictionaries
data = [
    {'Name': 'Vanessa', 'Age': 18, 'ML mark': 50},
    {'Name': 'Christine', 'Age': 20, 'ML mark': 70},
    {'Name': 'Peter', 'Age': 25, 'ML mark': 82},
    {'Name': 'Diana', 'Age': 30, 'ML mark': 63},
    {'Name': 'Racheal', 'Age': 35, 'ML mark': 38}
]

example_df2 = pd.DataFrame(data)
example_df2

        Name  Age  ML mark
0    Vanessa   18       50
1  Christine   20       70
2      Peter   25       82
3      Diana   30       63
4    Racheal   35       38

In [15]:
# creating a dataframe from two lists
ml_age = [18, 20, 25, 30, 35]
example_df3 = pd.DataFrame(zip(ml_age, ml_marks), columns = ['Age', 'ML mark'])
example_df3

   Age  ML mark
0   18       50
1   20       70
2   25       82
3   30       63
4   35       38

In [16]:
# dataframe properties
example_df.shape

(5, 3)

In [18]:
example_df.columns.tolist()

['Name', 'Age', 'ML mark']

In [19]:
example_df.dtypes

Name         str
Age        int64
ML mark    int64
dtype: object

In [20]:
example_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Age      5 non-null      int64
 2   ML mark  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [21]:
# first 2 rows
example_df.head(2)

        Name  Age  ML mark
0    Vanessa   18       50
1  Christine   20       70

In [17]:
# last 2 rows ?
example_df.tail(2)

      Name  Age  ML mark
3    Diana   30       63
4  Racheal   35       38

In [22]:
# first 2 columns
example_df[["Name", "Age"]]

        Name  Age
0    Vanessa   18
1  Christine   20
2      Peter   25
3      Diana   30
4    Racheal   35

In [25]:
example_df.iloc[2:4, 1:3]

   Age  ML mark
2   25       82
3   30       63

In [ ]:
# the third and fourth rows and the last 2 columns

In [21]:
# single column
example_df['Age'] # or example_df.Age

0    18
1    20
2    25
3    30
4    35
Name: Age, dtype: int64

In [22]:
# multiple columns
example_df[['Name', 'Age']]

        Name  Age
0    Vanessa   18
1  Christine   20
2      Peter   25
3      Diana   30
4    Racheal   35

In [23]:
example_df.iloc[3]

Name       Diana
Age           30
ML mark       63
Name: 3, dtype: object

In [ ]:
# example_df.iloc[:3, :2]  - what does this give you?

In [24]:
# filtering based on conditional statements
example_df[example_df.Age > 20]

      Name  Age  ML mark
2    Peter   25       82
3    Diana   30       63
4  Racheal   35       38

In [25]:
print(example_df[(example_df['Age'] > 20) & (example_df['ML mark'] > 80)])

    Name  Age  ML mark
2  Peter   25       82

In [27]:
# creating a new column
example_df['New ML mark'] = example_df['ML mark'] + 3
example_df.head(1)

      Name  Age  ML mark  New ML mark
0  Vanessa   18       50           53

In [28]:
# using a lambda function
example_df['New Age'] = example_df['Age'].apply(lambda x: x+3)
example_df.head(1)

      Name  Age  ML mark  New ML mark  New Age
0  Vanessa   18       50           53       21

In [29]:
example_df['Age group'] = example_df['Age'].apply(lambda x: 'Teenager' if x<=18 else 'Adult')
example_df

        Name  Age  ML mark  New ML mark  New Age Age group
0    Vanessa   18       50           53       21  Teenager
1  Christine   20       70           73       23     Adult
2      Peter   25       82           85       28     Adult
3      Diana   30       63           66       33     Adult
4    Racheal   35       38           41       38     Adult

### **Exercise**
a. Create a dataframe with 30 rows containing fictional house data (price, size, bedrooms, location). The dataframe must include the following columns: price (in UGX), size_sqm, bedrooms, bathrooms, location, year_built, and property_type (e.g. apartment, bungalow, mansion). Use numpy to randomly generate the numerical columns with realistic constraints. For example, larger house have a higher price. Set a random seed for reproducibility. Finally, display the shape, dtypes, and first 8 rows of the dataframe. <br/><br/> 
b. From the dataframe above, extract all houses that are located in two particular locations that have a price above a specified threshold, and at least 3 bedrooms. Reset the index of the result. What is the average price of the filtered results? Which property type appears most frequently in the filtered results? <br/><br/>
c. Extract rows 5 to 14 (inclusive) and columns 2 and 3 only. With the result, rename the columns to something meaningful. Calculate the mean and standard deviation of each column in the slice. Display the row from the slice that has the highest value in the first of the two selected columns. <br/><br/>
d. Create a new column *deposit* that is 10% of the price using four different approaches and verify that they all give the same result.

In [11]:
np.random.seed(42)
n = 30

In [ ]:
#size per sqm
size_sqm = np.random.randint(30, 400, n)
size_sqm[:5]

array([ 88, 199, 217, 300, 219], dtype=int32)

In [ ]:
#no of bedrooms
bedrooms = np.random.randint(1,7,n)
bedrooms[:6]

array([1, 4, 3, 6, 5, 3], dtype=int32)

In [ ]:
#no of bathrooms
bathrooms = np.random.randint(1,4,n)
bathrooms[:3]

array([1, 1, 2], dtype=int32)

In [ ]:
#year built
year_built = np.random.randint(1990,2025,n)
year_built[:6]

array([2019, 2018, 1995, 2024, 2013, 2018], dtype=int32)

In [28]:
#property type
property_types = ['Apartment','Bungalow','Mansion']
property_type = np.random.choice(property_types,n)
property_type[:3]

array(['Mansion', 'Bungalow', 'Apartment'], dtype='<U9')

In [39]:
#location
locations = ['Surburb','Village','Town','Hilly area']
location = np.random.choice(locations, n)
location[:6]

array(['Village', 'Village', 'Village', 'Village', 'Village', 'Town'],
      dtype='<U10')

In [ ]:
#price meaning larger houses are more expensive
price_in_UGX_per_sqm = np.random.randint(650_000,1_000_000,n)
price = size_sqm * price_in_UGX_per_sqm
price[:3]

array([ 58030280, 164204850, 215041792], dtype=int32)

In [40]:
#creating the dataframe
exercise_df = pd.DataFrame({
    'Price_UGX':price,
    'Size_sqm':size_sqm,
    'bedrooms':bedrooms,
    'bathrooms':bathrooms,
    'year-built':year_built,
    'location':location,
    'property_type':property_type
    
})

In [41]:
exercise_df.shape

(30, 7)

In [42]:
exercise_df.dtypes

Price_UGX        int32
Size_sqm         int32
bedrooms         int32
bathrooms        int32
year-built       int32
location           str
property_type      str
dtype: object

In [43]:
exercise_df.head(8)

   Price_UGX  Size_sqm  bedrooms  bathrooms  year-built location property_type
0   58030280        88         1          1        2019  Village       Mansion
1  164204850       199         4          1        2018  Village      Bungalow
2  215041792       217         3          2        1995  Village     Apartment
3  210387900       300         6          1        2024  Village       Mansion
4  159603039       219         5          2        2013  Village      Bungalow
5  171660900       204         3          1        2018     Town       Mansion
6   64815680        80         4          1        2020  Surburb     Apartment
7  344467251       393         4          3        2024     Town     Apartment

In [50]:
#part b
filtered_df = exercise_df[
    (exercise_df['location'].isin(['Village','Town'])) &
    (exercise_df['Price_UGX'] > 50_000_000) &
    (exercise_df['bedrooms'] >= 3)
]

In [53]:
#reset index
filtered_df = filtered_df.reset_index(drop=True)
filtered_df

   Price_UGX  Size_sqm  bedrooms  bathrooms  year-built location property_type
0  164204850       199         4          1        2018  Village      Bungalow
1  215041792       217         3          2        1995  Village     Apartment
2  210387900       300         6          1        2024  Village       Mansion
3  159603039       219         5          2        2013  Village      Bungalow
4  171660900       204         3          1        2018     Town       Mansion
5  344467251       393         4          3        2024     Town     Apartment
6  242924409       273         4          1        2010  Village       Mansion
7  158869588       164         3          3        1992     Town     Apartment
8  268354548       396         3          2        2022     Town     Apartment

In [54]:
#average price of the filtered
filtered_df['Price_UGX'].mean()

np.float64(215057141.8888889)

In [55]:
#most frequent property type
filtered_df['property_type'].mode()[0]

'Apartment'

In [56]:
# rows 5 to 14(inclusive)
extracted = exercise_df.iloc[5:15,2:4]
extracted

    bedrooms  bathrooms
5          3          1
6          4          1
7          4          3
8          3          3
9          4          1
10         3          1
11         2          3
12         3          3
13         3          3
14         4          2

In [58]:
extracted_df = extracted.rename(columns={
    'bedrooms':'num-bedrooms',
    'bathrooms':'num-bathrooms'
})
extracted_df

    num-bedrooms  num-bathrooms
5              3              1
6              4              1
7              4              3
8              3              3
9              4              1
10             3              1
11             2              3
12             3              3
13             3              3
14             4              2

In [59]:
#mean 
extracted_df.mean()

num-bedrooms     3.3
num-bathrooms    2.1
dtype: float64

In [60]:
#standard deviation
extracted_df.std()

num-bedrooms     0.674949
num-bathrooms    0.994429
dtype: float64

In [61]:
#row with highest value
extracted_df.loc[extracted_df['num-bedrooms'].idxmax()]

num-bedrooms     4
num-bathrooms    1
Name: 6, dtype: int32

In [62]:
#approach 1
exercise_df['first-deposit']= exercise_df['Price_UGX'] * 0.10
exercise_df.head()

,Price_UGX,Size_sqm,bedrooms,bathrooms,year-built,location,property_type,first-deposit
0,58030280,88,1,1,2019,Village,Mansion,5803028.0
1,164204850,199,4,1,2018,Village,Bungalow,16420485.0
2,215041792,217,3,2,1995,Village,Apartment,21504179.2
3,210387900,300,6,1,2024,Village,Mansion,21038790.0
4,159603039,219,5,2,2013,Village,Bungalow,15960303.9

In [64]:
#approach 2
exercise_df['second-deposit']= exercise_df['Price_UGX'] /10
exercise_df.head()

,Price_UGX,Size_sqm,bedrooms,bathrooms,year-built,location,property_type,first-deposit,second-deposit
0,58030280,88,1,1,2019,Village,Mansion,5803028.0,5803028.0
1,164204850,199,4,1,2018,Village,Bungalow,16420485.0,16420485.0
2,215041792,217,3,2,1995,Village,Apartment,21504179.2,21504179.2
3,210387900,300,6,1,2024,Village,Mansion,21038790.0,21038790.0
4,159603039,219,5,2,2013,Village,Bungalow,15960303.9,15960303.9

In [65]:
#approach 3
exercise_df['third-deposit']= exercise_df['Price_UGX'].apply(lambda x: x * 0.10)
exercise_df.head()

,Price_UGX,Size_sqm,bedrooms,bathrooms,year-built,location,property_type,first-deposit,second-deposit,third-deposit
0,58030280,88,1,1,2019,Village,Mansion,5803028.0,5803028.0,5803028.0
1,164204850,199,4,1,2018,Village,Bungalow,16420485.0,16420485.0,16420485.0
2,215041792,217,3,2,1995,Village,Apartment,21504179.2,21504179.2,21504179.2
3,210387900,300,6,1,2024,Village,Mansion,21038790.0,21038790.0,21038790.0
4,159603039,219,5,2,2013,Village,Bungalow,15960303.9,15960303.9,15960303.9

In [66]:
#approach 4
exercise_df = exercise_df.assign(
    deposit_4 = exercise_df['Price_UGX'] * 0.10
) 
exercise_df.head()

,Price_UGX,Size_sqm,bedrooms,bathrooms,year-built,location,property_type,first-deposit,second-deposit,third-deposit,deposit_4
0,58030280,88,1,1,2019,Village,Mansion,5803028.0,5803028.0,5803028.0,5803028.0
1,164204850,199,4,1,2018,Village,Bungalow,16420485.0,16420485.0,16420485.0,16420485.0
2,215041792,217,3,2,1995,Village,Apartment,21504179.2,21504179.2,21504179.2,21504179.2
3,210387900,300,6,1,2024,Village,Mansion,21038790.0,21038790.0,21038790.0,21038790.0
4,159603039,219,5,2,2013,Village,Bungalow,15960303.9,15960303.9,15960303.9,15960303.9

In [70]:
#comparison of the approaches
(
    (exercise_df["first-deposit"] == exercise_df["second-deposit"]) &
    (exercise_df["first-deposit"] == exercise_df["third-deposit"]) &
    (exercise_df["first-deposit"] == exercise_df["deposit_4"])
).all()

np.False_